version: '3'

# Development environment only, not to be used in production

services:

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.0.1
    command: mlflow server --host 0.0.0.0
    ports:
      - 5000:5000
    
  lakefs:
    image: treeverse/lakefs
    ports:
      - 8001:8000
    command: run --local-settings

  minio:
    image: quay.io/minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    ports:
      # - 9000:9000
      # - 9001:9001
      - 9002:9000
      - 9003:9001
    command: server /data --console-address ":9001"
