version: '3'

# Development environment only, not to be used in production

services:

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.0.1
    ports:
      - 5000:5000
    # command: mlflow server --host 0.0.0.0 --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB} --default-artifact-root s3://bucket_name
    # TODO: Clean commands below with a custom Dockerfile
    command: sh -c "
      apt-get update && apt-get install -y libpq-dev gcc python3-dev &&
      pip install psycopg2 &&
      mlflow server --host 0.0.0.0 --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    
  lakefs:
    image: treeverse/lakefs
    ports:
      - 8001:8000
    command: run --local-settings

  minio:
    image: quay.io/minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    ports:
      # - 9000:9000
      # - 9001:9001
      - 9002:9000
      - 9003:9001
    command: server /data --console-address ":9001"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
