import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import dataset from "../../datasets/merged-small.json"
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1 className={inter.className}>DNN Full Stack Production(ish) Recommendation System</h1>
        </div>

        <div className={styles.grid}>
          {dataset.data.slice(0, 50).map((movie) => 
            <a
              href={movie["Imdb Link"]}
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
              key={movie.movieId}
            >
              <img
                src={movie.Poster}
                alt={movie.title}
                className={styles.vercelLogo}
                width={100}
              />
              <h2 className={inter.className}>
                {movie.title} <span>-&gt;</span>
              </h2>
            </a>
          )}
        </div>
      </main>
    </>
  )
}
